import * as VTable from '../../src';

const PivotTable = VTable.PivotTable;
const CONTAINER_ID = 'vTable';

const imgUrl =
  'https://p3-heycan-hgt-sign.byteimg.com/tos-cn-i-3jr8j4ixpe/399f656fe0634bcfbe180e572d2dc8e6~tplv-3jr8j4ixpe-resize:400:400.png?lk3s=43402efa&x-expires=1773847788&x-signature=zj%2F22SPfvlM0V4SDESHVbYNzXfo%3D&quot';

export const records = [
  {
    '1': '交互功能族',
    '3': '语音交互',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '基础语音',
    is_diff: true
  },
  {
    '1': '交互功能族',
    '3': '第三方音箱控制',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '视频通话',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '地毯检测',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '超声波 + 视觉',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '悬崖防跌落',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '导航',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '凸起雷达+视觉',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '机身高度',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '10.2 cm',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '越障高度',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '2 cm',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '避障能力',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '前向+侧向',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '2': '脏污检测',
    '3': '拖地闭环',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '视觉+光学传感器',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '脏污检测',
    '3': '扫地闭环',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '3': '吸力',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '7000 Pa',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '3': '地毯清洁',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '增压吸尘',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷控速',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷数量',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '单',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷抬升',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷机械臂',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷结构',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '普通边刷',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷控速',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷抬升',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷结构',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '单胶刷',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '集尘方式',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '机身尘盒',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '集尘容量',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '0.35 L',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '尘盒干燥',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '边角拖地',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '拖布外扩',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '机身水箱',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '自动补水',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '地板养护',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '热水拖地',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布结构',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '双圆盘旋转拖布',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布抬升',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖地力度调节',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布自动拆卸',
    '4': '机器人',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '基站控制',
    '4': '基站',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '自动上下水',
    '4': '基站',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '选配',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '基站自清洁',
    '4': '基站',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '小基站',
    '4': '基站',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘能力',
    '4': '基站',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '基站集尘袋',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘容量',
    '4': '基站',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '2.7 L',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘烘干',
    '4': '基站',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘紫外线抑菌',
    '4': '基站',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '清水箱容量',
    '4': '基站',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '4 L',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '污水箱容量',
    '4': '基站',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '3.5 L',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '电解水',
    '4': '基站',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '银离子抑菌',
    '4': '基站',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '选配',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '污水箱除臭',
    '4': '基站',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '机仓紫外线抑菌',
    '4': '基站',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '热水洗拖布',
    '4': '基站',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '智控热水',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '拖布烘干',
    '4': '基站',
    brand: '某石',
    product: 'P10 Pro',
    first_pic: imgUrl,
    release_time: '2023-08-29',
    first_price: 3999,
    product_feature: '标配',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '语音交互',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '语音大模型',
    is_diff: true
  },
  {
    '1': '交互功能族',
    '3': '第三方音箱控制',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '视频通话',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '地毯检测',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '超声波 + 视觉',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '悬崖防跌落',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '导航',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '凸起雷达+视觉',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '机身高度',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '10.3 cm',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '越障高度',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '4 cm',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '避障能力',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '前向+侧向',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '2': '脏污检测',
    '3': '拖地闭环',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '光学传感器',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '脏污检测',
    '3': '扫地闭环',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '3': '吸力',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '18500 Pa',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '3': '地毯清洁',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '增压吸尘',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷控速',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷数量',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '单',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷抬升',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷机械臂',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷结构',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '防缠绕边刷',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷控速',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷抬升',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷结构',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '气旋导流双毛胶对刷',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '集尘方式',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '机身尘盒',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '集尘容量',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '0.35 L',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '尘盒干燥',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '边角拖地',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '拖布外扩',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '机身水箱',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '自动补水',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '地板养护',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '热水拖地',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布结构',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '双圆盘旋转拖布',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布抬升',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖地力度调节',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布自动拆卸',
    '4': '机器人',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '基站控制',
    '4': '基站',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '自动上下水',
    '4': '基站',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '选配',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '基站自清洁',
    '4': '基站',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '小基站',
    '4': '基站',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘能力',
    '4': '基站',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '基站集尘袋',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘容量',
    '4': '基站',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '2.5 L',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘烘干',
    '4': '基站',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘紫外线抑菌',
    '4': '基站',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '清水箱容量',
    '4': '基站',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '4 L',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '污水箱容量',
    '4': '基站',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '3.5 L',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '电解水',
    '4': '基站',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '银离子抑菌',
    '4': '基站',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '选配',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '污水箱除臭',
    '4': '基站',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '标配',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '机仓紫外线抑菌',
    '4': '基站',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '热水洗拖布',
    '4': '基站',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '智控热水',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '拖布烘干',
    '4': '基站',
    brand: '某石',
    product: 'P20 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '标配',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '语音交互',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '语音大模型',
    is_diff: true
  },
  {
    '1': '交互功能族',
    '3': '第三方音箱控制',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '视频通话',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '地毯检测',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '超声波 + 视觉',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '悬崖防跌落',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '导航',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '凸起雷达+视觉',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '机身高度',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '10.38 cm',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '越障高度',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '2.2 cm',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '避障能力',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '前向+侧向',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '2': '脏污检测',
    '3': '拖地闭环',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '视觉+光学传感器',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '脏污检测',
    '3': '扫地闭环',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '3': '吸力',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '11000 Pa',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '3': '地毯清洁',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '增压吸尘',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷控速',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷数量',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '单',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷抬升',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷机械臂',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷结构',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '防缠绕边刷',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷控速',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷抬升',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷结构',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '剃刀式割毛滚刷',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '集尘方式',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '机身尘盒',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '集尘容量',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '0.3 L',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '尘盒干燥',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '边角拖地',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '拖布外扩 + 扭屁股',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '机身水箱',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '自动补水',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '地板养护',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '热水拖地',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布结构',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '双圆盘旋转拖布',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布抬升',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖地力度调节',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布自动拆卸',
    '4': '机器人',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '基站控制',
    '4': '基站',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '自动上下水',
    '4': '基站',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '选配',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '基站自清洁',
    '4': '基站',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '小基站',
    '4': '基站',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘能力',
    '4': '基站',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '基站集尘袋',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘容量',
    '4': '基站',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '3.2 L',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘烘干',
    '4': '基站',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘紫外线抑菌',
    '4': '基站',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '清水箱容量',
    '4': '基站',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '4.5 L',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '污水箱容量',
    '4': '基站',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '4 L',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '电解水',
    '4': '基站',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '银离子抑菌',
    '4': '基站',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '标配',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '污水箱除臭',
    '4': '基站',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '机仓紫外线抑菌',
    '4': '基站',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '热水洗拖布',
    '4': '基站',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '智控热水',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '拖布烘干',
    '4': '基站',
    brand: '某觅',
    product: 'S30 Pro Ultra',
    first_pic: imgUrl,
    release_time: '2024-02-02',
    first_price: 4299,
    product_feature: '标配',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '语音交互',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '语音大模型',
    is_diff: true
  },
  {
    '1': '交互功能族',
    '3': '第三方音箱控制',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '视频通话',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '地毯检测',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '超声波 + 视觉',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '悬崖防跌落',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '导航',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '凸起雷达+视觉',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '机身高度',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '10.38 cm',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '越障高度',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '2.2 cm',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '避障能力',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '前向+侧向',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '2': '脏污检测',
    '3': '拖地闭环',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '视觉+光学传感器',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '脏污检测',
    '3': '扫地闭环',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '3': '吸力',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '12000 Pa',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '3': '地毯清洁',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '增压吸尘',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷控速',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷数量',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '单',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷抬升',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷机械臂',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷结构',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '防缠绕边刷',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷控速',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷抬升',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷结构',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '剃刀式割毛滚刷',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '集尘方式',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '机身尘盒',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '集尘容量',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '0.3 L',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '尘盒干燥',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '边角拖地',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '拖布外扩 + 扭屁股',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '机身水箱',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '自动补水',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '地板养护',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '热水拖地',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布结构',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '双圆盘旋转拖布',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布抬升',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖地力度调节',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布自动拆卸',
    '4': '机器人',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '基站控制',
    '4': '基站',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '自动上下水',
    '4': '基站',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '选配',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '基站自清洁',
    '4': '基站',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '小基站',
    '4': '基站',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘能力',
    '4': '基站',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '基站集尘袋',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘容量',
    '4': '基站',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '3.2 L',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘烘干',
    '4': '基站',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘紫外线抑菌',
    '4': '基站',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '清水箱容量',
    '4': '基站',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '4.5 L',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '污水箱容量',
    '4': '基站',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '4 L',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '电解水',
    '4': '基站',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '银离子抑菌',
    '4': '基站',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '标配',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '污水箱除臭',
    '4': '基站',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '选配',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '机仓紫外线抑菌',
    '4': '基站',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '热水洗拖布',
    '4': '基站',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '智控热水',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '拖布烘干',
    '4': '基站',
    brand: '某觅',
    product: 'S40',
    first_pic: imgUrl,
    release_time: '2024-05-02',
    first_price: 4699,
    product_feature: '标配',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '语音交互',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '基础语音',
    is_diff: true
  },
  {
    '1': '交互功能族',
    '3': '第三方音箱控制',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '视频通话',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '地毯检测',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '超声波',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '悬崖防跌落',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '导航',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '凸起雷达+视觉',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '机身高度',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '10.4 cm',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '越障高度',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '2 cm',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '避障能力',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '前向+侧向',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '2': '脏污检测',
    '3': '拖地闭环',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '光学传感器',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '脏污检测',
    '3': '扫地闭环',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '3': '吸力',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '11000 Pa',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '3': '地毯清洁',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '增压吸尘',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷控速',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷数量',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '单',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷抬升',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷机械臂',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷结构',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '普通边刷',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷控速',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷抬升',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷结构',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '毛胶滚刷',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '集尘方式',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '机身尘盒',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '集尘容量',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '0.3 L',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '尘盒干燥',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '边角拖地',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '拖布外扩',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '机身水箱',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '自动补水',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '地板养护',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '热水拖地',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布结构',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '双圆盘旋转拖布',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布抬升',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖地力度调节',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布自动拆卸',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '基站控制',
    '4': '基站',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '自动上下水',
    '4': '基站',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '选配',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '基站自清洁',
    '4': '基站',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '小基站',
    '4': '基站',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘能力',
    '4': '基站',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '基站集尘袋',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘容量',
    '4': '基站',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '3.4 L',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘烘干',
    '4': '基站',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘紫外线抑菌',
    '4': '基站',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '清水箱容量',
    '4': '基站',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '4 L',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '污水箱容量',
    '4': '基站',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '3.5 L',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '电解水',
    '4': '基站',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '银离子抑菌',
    '4': '基站',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '选配',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '污水箱除臭',
    '4': '基站',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '机仓紫外线抑菌',
    '4': '基站',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '热水洗拖布',
    '4': '基站',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '70℃',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '拖布烘干',
    '4': '基站',
    brand: '某沃斯',
    product: 'T30 PRO',
    first_pic: imgUrl,
    release_time: '2024-02-04',
    first_price: 3999,
    product_feature: '标配',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '语音交互',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '语音大模型',
    is_diff: true
  },
  {
    '1': '交互功能族',
    '3': '第三方音箱控制',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '视频通话',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '地毯检测',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '超声波 + 视觉',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '悬崖防跌落',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '导航',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '隐藏雷达+视觉',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '机身高度',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '8.1 cm',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '越障高度',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '2 cm',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '障碍躲避',
    '3': '避障能力',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '前向+侧向',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '2': '脏污检测',
    '3': '拖地闭环',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '视觉+光学传感器',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '2': '脏污检测',
    '3': '扫地闭环',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '视觉',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '3': '吸力',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '15800 Pa',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '3': '地毯清洁',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '增压吸尘',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷控速',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷数量',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '单',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷抬升',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷机械臂',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '边刷',
    '3': '边刷结构',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '普通边刷',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷控速',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷抬升',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '中滚刷',
    '3': '中滚刷结构',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '毛胶滚刷',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '集尘方式',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '机身尘盒',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '集尘容量',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '0.26 L',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '机器人集尘',
    '3': '尘盒干燥',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '边角拖地',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '拖布外扩',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '机身水箱',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '自动补水',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '地板养护',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '热水拖地',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布结构',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '双圆盘旋转拖布',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布抬升',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖地力度调节',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '2': '拖布',
    '3': '拖布自动拆卸',
    '4': '机器人',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '交互功能族',
    '3': '基站控制',
    '4': '基站',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '自动上下水',
    '4': '基站',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '选配',
    is_diff: false
  },
  {
    '1': '智能功能族',
    '3': '基站自清洁',
    '4': '基站',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '智能功能族',
    '3': '小基站',
    '4': '基站',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '✅',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘能力',
    '4': '基站',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '基站集尘袋',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘容量',
    '4': '基站',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '3.4 L',
    is_diff: true
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘烘干',
    '4': '基站',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '扫地功能族',
    '2': '基站集尘',
    '3': '集尘紫外线抑菌',
    '4': '基站',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '清水箱容量',
    '4': '基站',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '4 L',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '污水箱容量',
    '4': '基站',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '3.5 L',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '电解水',
    '4': '基站',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '银离子抑菌',
    '4': '基站',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '选配',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '污水箱除臭',
    '4': '基站',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '机仓紫外线抑菌',
    '4': '基站',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '❌',
    is_diff: false
  },
  {
    '1': '拖地功能族',
    '3': '热水洗拖布',
    '4': '基站',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '70℃',
    is_diff: true
  },
  {
    '1': '拖地功能族',
    '3': '拖布烘干',
    '4': '基站',
    brand: '某沃斯',
    product: 'T50 Pro',
    first_pic: imgUrl,
    release_time: '2024-08-26',
    first_price: 3999,
    product_feature: '标配',
    is_diff: false
  }
];

export function createTable() {
  const option: VTable.PivotTableConstructorOptions = {
    container: document.getElementById(CONTAINER_ID),
    records,
    rowTree: [
      {
        value: '机器人',
        children: [
          {
            value: '交互功能族',
            children: [
              {
                value: '语音交互',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '213_3',
                hide: false
              },
              {
                value: '第三方音箱控制',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '2_3',
                hide: false
              },
              {
                value: '视频通话',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '3_3',
                hide: false
              }
            ],
            dimensionKey: '1',
            hierarchyState: 'expand',
            nodeKey: '1_1',
            hide: false
          },
          {
            value: '智能功能族',
            children: [
              {
                value: '地毯检测',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '15_3',
                hide: false
              },
              {
                value: '悬崖防跌落',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '16_3',
                hide: false
              },
              {
                value: '导航',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '17_3',
                hide: false
              },
              {
                value: '障碍躲避',
                children: [
                  {
                    value: '机身高度',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '199_3',
                    hide: false
                  },
                  {
                    value: '越障高度',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '9_3',
                    hide: false
                  },
                  {
                    value: '避障能力',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '10_3',
                    hide: false
                  }
                ],
                dimensionKey: '2',
                hierarchyState: 'expand',
                nodeKey: '1_2',
                hide: false
              },
              {
                value: '脏污检测',
                children: [
                  {
                    value: '拖地闭环',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '18_3',
                    hide: false
                  },
                  {
                    value: '扫地闭环',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '20_3',
                    hide: false
                  }
                ],
                dimensionKey: '2',
                hierarchyState: 'expand',
                nodeKey: '3_2',
                hide: false
              }
            ],
            dimensionKey: '1',
            hierarchyState: 'expand',
            nodeKey: '3_1',
            hide: false
          },
          {
            value: '扫地功能族',
            children: [
              {
                value: '吸力',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '46_3',
                hide: false
              },
              {
                value: '地毯清洁',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '47_3',
                hide: false
              },
              {
                value: '边刷',
                children: [
                  {
                    value: '边刷控速',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '33_3',
                    hide: false
                  },
                  {
                    value: '边刷数量',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '34_3',
                    hide: false
                  },
                  {
                    value: '边刷抬升',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '187_3',
                    hide: false
                  },
                  {
                    value: '边刷机械臂',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '186_3',
                    hide: false
                  },
                  {
                    value: '边刷结构',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '198_3',
                    hide: false
                  }
                ],
                dimensionKey: '2',
                hierarchyState: 'expand',
                nodeKey: '5_2',
                hide: false
              },
              {
                value: '中滚刷',
                children: [
                  {
                    value: '中滚刷控速',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '35_3',
                    hide: false
                  },
                  {
                    value: '中滚刷抬升',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '36_3',
                    hide: false
                  },
                  {
                    value: '中滚刷结构',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '37_3',
                    hide: false
                  }
                ],
                dimensionKey: '2',
                hierarchyState: 'expand',
                nodeKey: '6_2',
                hide: false
              },
              {
                value: '机器人集尘',
                children: [
                  {
                    value: '集尘方式',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '38_3',
                    hide: false
                  },
                  {
                    value: '集尘容量',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '39_3',
                    hide: false
                  },
                  {
                    value: '尘盒干燥',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '195_3',
                    hide: false
                  }
                ],
                dimensionKey: '2',
                hierarchyState: 'expand',
                nodeKey: '7_2',
                hide: false
              }
            ],
            dimensionKey: '1',
            hierarchyState: 'expand',
            nodeKey: '7_1',
            hide: false
          },
          {
            value: '拖地功能族',
            children: [
              {
                value: '边角拖地',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '27_3',
                hide: false
              },
              {
                value: '机身水箱',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '97_3',
                hide: false
              },
              {
                value: '地板养护',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '192_3',
                hide: false
              },
              {
                value: '热水拖地',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '209_3',
                hide: false
              },
              {
                value: '拖布',
                children: [
                  {
                    value: '拖布结构',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '21_3',
                    hide: false
                  },
                  {
                    value: '拖布抬升',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '22_3',
                    hide: false
                  },
                  {
                    value: '拖地力度调节',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '24_3',
                    hide: false
                  },
                  {
                    value: '拖布自动拆卸',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '191_3',
                    hide: false
                  }
                ],
                dimensionKey: '2',
                hierarchyState: 'expand',
                nodeKey: '4_2',
                hide: false
              }
            ],
            dimensionKey: '1',
            hierarchyState: 'expand',
            nodeKey: '5_1',
            hide: false
          }
        ],
        dimensionKey: '4',
        hierarchyState: 'expand',
        nodeKey: '1_4',
        hide: false
      },
      {
        value: '基站',
        children: [
          {
            value: '交互功能族',
            children: [
              {
                value: '基站控制',
                dimensionKey: '3'
              }
            ],
            dimensionKey: '1'
          },
          {
            value: '智能功能族',
            children: [
              {
                value: '自动上下水',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '211_3',
                hide: false
              },
              {
                value: '基站自清洁',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '8_3',
                hide: false
              },
              {
                value: '小基站',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '193_3',
                hide: false
              }
            ],
            dimensionKey: '1',
            hierarchyState: 'expand',
            nodeKey: '4_1',
            hide: false
          },
          {
            value: '扫地功能族',
            children: [
              {
                value: '基站集尘',
                children: [
                  {
                    value: '集尘能力',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '42_3',
                    hide: false
                  },
                  {
                    value: '集尘容量',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '43_3',
                    hide: false
                  },
                  {
                    value: '集尘烘干',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '44_3',
                    hide: false
                  },
                  {
                    value: '集尘紫外线抑菌',
                    children: [],
                    dimensionKey: '3',
                    hierarchyState: 'expand',
                    nodeKey: '45_3',
                    hide: false
                  }
                ],
                dimensionKey: '2',
                hierarchyState: 'expand',
                nodeKey: '8_2',
                hide: false
              }
            ],
            dimensionKey: '1',
            hierarchyState: 'expand',
            nodeKey: '8_1',
            hide: false
          },
          {
            value: '拖地功能族',
            children: [
              {
                value: '清水箱容量',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '28_3',
                hide: false
              },
              {
                value: '污水箱容量',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '29_3',
                hide: false
              },
              {
                value: '电解水',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '32_3',
                hide: false
              },
              {
                value: '银离子抑菌',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '95_3',
                hide: false
              },
              {
                value: '污水箱除臭',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '189_3',
                hide: false
              },
              {
                value: '机仓紫外线抑菌',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '190_3',
                hide: false
              },
              {
                value: '热水洗拖布',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '30_3',
                hide: false
              },
              {
                value: '拖布烘干',
                children: [],
                dimensionKey: '3',
                hierarchyState: 'expand',
                nodeKey: '94_3',
                hide: false
              }
            ],
            dimensionKey: '1',
            hierarchyState: 'expand',
            nodeKey: '6_1',
            hide: false
          }
        ],
        dimensionKey: '4',
        hierarchyState: 'expand',
        nodeKey: '2_4',
        hide: false
      }
    ],
    rows: [
      {
        dimensionKey: '4',
        title: '模块',
        headerStyle: {
          bgColor: '#fff'
        }
      },
      {
        dimensionKey: '1',
        title: '分类',
        headerStyle: {
          bgColor: '#fff',
          fontWeight: 'normal'
        }
      },
      {
        dimensionKey: '2',
        title: '分组',
        headerStyle: {
          bgColor: '#fff',
          fontWeight: 'normal'
        }
      },
      {
        dimensionKey: '3',
        title: 'feature',
        headerStyle: {
          bgColor: '#fff',
          fontWeight: 'normal'
        }
      }
    ],
    columns: [
      {
        dimensionKey: 'brand',
        title: '品牌',
        headerStyle: {
          bgColor: '#fff',
          textAlign: 'center'
        }
      },
      {
        dimensionKey: 'product',
        title: '型号',
        headerStyle: {
          bgColor: '#fff',
          textAlign: 'center'
        }
      },
      {
        dimensionKey: 'first_pic',
        title: '图片',
        // imageAutoSizing: true, // 图片原始尺寸
        keepAspectRatio: true,
        headerType: 'image',
        width: 'auto'
      },
      {
        dimensionKey: 'release_time',
        title: '上市时间',
        headerStyle: {
          bgColor: '#fff',
          fontWeight: 'normal',
          textAlign: 'center'
        }
      },
      {
        dimensionKey: 'first_price',
        title: '价格',
        headerStyle: {
          bgColor: '#fff',
          fontWeight: 'normal',
          textAlign: 'center'
        }
      }
    ],
    indicators: [
      {
        cellType: 'text',
        indicatorKey: 'product_feature',
        title: 'product_feature',
        width: 'auto',
        showSort: false,
        style: {
          textAlign: 'center',
          bgColor: args => {
            const record = args.table.getCellRawRecord(args?.col, args?.row)?.[0];
            if (record?.is_diff) {
              return '#FEE6E4';
            }
            return '#fff';
          }
        }
      }
    ],
    corner: {
      titleOnDimension: 'column',
      headerStyle: {
        bgColor: '#DFEBE8'
      }
    },
    dataConfig: {
      aggregationRules: [
        {
          field: 'product_feature',
          indicatorKey: 'product_feature',
          aggregationType: 'NONE'
        }
      ]
    },
    hideIndicatorName: true,
    rowHierarchyType: 'tree',
    widthMode: 'autoWidth',
    rowHierarchyIndent: 20,
    rowHierarchyTextStartAlignment: true,
    columnHierarchyType: 'grid'
  };
  const tableInstance = new PivotTable(option);

  // 只为了方便控制太调试用，不要拷贝
  window.tableInstance = tableInstance;
}
